### ISSUE TITLE
The angle of the legs in the go1 simulation is wrong.

### ISSUE THREAD

**Issue by KCCT-Miyamoto** [qiayuanl/legged_control#53]
Hello. @qiayuanliao 
unitree_description empty_world.launch

The leg angle of go1 in the simulator appears to be 90 degrees different from the initial position. Can you tell me how to improve this?

![IMG_3686](https://github.com/qiayuanliao/legged_control/assets/39211139/67fdf0ee-63d6-4263-8624-8eec7cc868d2)

**Comment by Freaky1122** [comment]
Have you solved this problem?I met the same question

**Comment by LeonardoGMoraes** [comment]
Did someone solve this? I have the same problem.

**Comment by linzuen** [comment]
You can try to modify the parameters of https://github.com/qiayuanl/legged_control/blob/master/legged_examples/legged_unitree/legged_unitree_description/urdf/common/leg.xacro#L189-L190  to 0.2

**Comment by KCCT-Miyamoto** [comment]
Thanks!! I was able to run the simulation.
