### ISSUE TITLE
提问legged control中WBC相关问题

### ISSUE THREAD

**Issue by juanvon** [qiayuanl/legged_control#57]
我看到知乎文档对WBC的描述是采用层次优化的方法，参考文章也是层次优化的wbc，但是代码中最终为何使用的是WeightedWBC呢？是权重的方法更好吗？
![image](https://github.com/qiayuanl/legged_control/assets/87421767/9314a7e4-891e-45a2-a8c8-1ecd0a4ee496)

**Comment by szw123** [comment]
Hello, I also encountered the same confusion while reading the code. Could you tell me how you understood it? Thx

**Comment by zzzzyyyjjj** [comment]
我也有同样的困惑！请问有没有基于权重的相关资料呀
