### ISSUE TITLE
gazebo 仿真中的关节去哪看

### ISSUE THREAD

**Issue by JACKLiuDay** [qiayuanl/legged_control#76]
感谢作者的开源工作。想问下gazebo里面跑起来机器人以后，虚拟的关节数据在哪里看呢

**Comment by LianzhaoZhang** [comment]
可以用plotjugger可视化

**Comment by JACKLiuDay** [comment]
> 可以用plotjugger可视化

具体看哪个话题啊，我看mpc_observation话题的input里面是关节的期望速度，仿真里反馈的关节速度有办法用plotjugger看吗
